ALTER TABLE scm_order_stock drop column if exists seller_id;
ALTER TABLE scm_suppliers_goods_daily drop column if exists suppliers_id;
ALTER TABLE scm_supplier_price_plan drop column if exists supplier_id;
ALTER TABLE scm_good_units drop column if exists unit_id;
ALTER TABLE scm_goods drop column if exists base_unit_id;
ALTER TABLE scm_supplier_price_plan drop column if exists util_id;
ALTER TABLE scm_shop drop column if exists brand_id;
ALTER TABLE scm_shop drop column if exists supply_plan_id;
ALTER TABLE scm_goods drop column if exists util_id;

DROP TABLE IF EXISTS scm_seller;
DROP TABLE IF EXISTS st_accounts CASCADE;
DROP TABLE IF EXISTS st_bill_list CASCADE;
DROP TABLE IF EXISTS st_daily_count CASCADE;
DROP TABLE IF EXISTS st_daily_count_items CASCADE;
DROP TABLE IF EXISTS st_daily_sales CASCADE;
DROP TABLE IF EXISTS st_daily_sales_detail CASCADE;
DROP TABLE IF EXISTS st_food_category CASCADE;
DROP TABLE IF EXISTS st_food_item CASCADE;
DROP TABLE IF EXISTS st_food_item_copy CASCADE;
DROP TABLE IF EXISTS st_food_item_copy_on CASCADE;
DROP TABLE IF EXISTS st_ingredient CASCADE;
DROP TABLE IF EXISTS st_ingredient_copy CASCADE;
DROP TABLE IF EXISTS st_ingredient_types CASCADE;
DROP TABLE IF EXISTS st_inventory_allocation CASCADE;
DROP TABLE IF EXISTS st_inventory_count CASCADE;
DROP TABLE IF EXISTS st_inventory_detail CASCADE;
DROP TABLE IF EXISTS st_inventory_items CASCADE;
DROP TABLE IF EXISTS st_inventory_miscount CASCADE;
DROP TABLE IF EXISTS st_inventory_single CASCADE;
DROP TABLE IF EXISTS st_kitchen_department CASCADE;
DROP TABLE IF EXISTS st_kitchen_department_goods CASCADE;
DROP TABLE IF EXISTS st_member_account CASCADE;
DROP TABLE IF EXISTS st_menu CASCADE;
DROP TABLE IF EXISTS st_org CASCADE;
DROP TABLE IF EXISTS st_predict_daily_sales CASCADE;
DROP TABLE IF EXISTS st_predict_daily_sales_details CASCADE;
DROP TABLE IF EXISTS st_predict_order CASCADE;
DROP TABLE IF EXISTS st_predict_order_details CASCADE;
DROP TABLE IF EXISTS st_safe_store_goods CASCADE;
DROP TABLE IF EXISTS st_safe_store_goods_copy CASCADE;
DROP TABLE IF EXISTS st_sales_plan CASCADE;
DROP TABLE IF EXISTS st_sales_plan_items CASCADE;
DROP TABLE IF EXISTS st_settle_details CASCADE;
DROP TABLE IF EXISTS st_shop_sales_details CASCADE;
DROP TABLE IF EXISTS st_shop_section CASCADE;
DROP TABLE IF EXISTS st_shop_table CASCADE;
DROP TABLE IF EXISTS st_store_account CASCADE;

DROP VIEW IF EXISTS combined_goods_prices;
DROP VIEW IF EXISTS view_price_plan_goods;
DROP TABLE IF EXISTS scm_goods_price;
DROP TABLE IF EXISTS big_org CASCADE;
DROP TABLE IF EXISTS com_main_unit CASCADE;
DROP TABLE IF EXISTS flyway_schema_history;
DROP TABLE IF EXISTS migration;
DROP TABLE IF EXISTS scm_account_role;
DROP TABLE IF EXISTS scm_admin_token;
DROP TABLE IF EXISTS scm_admin;
DROP TABLE IF EXISTS scm_admin_group CASCADE;
DROP TABLE IF EXISTS scm_admin_group_scm_shop;
DROP TABLE IF EXISTS scm_brand_account;
DROP TABLE IF EXISTS scm_goods_img;
DROP TABLE IF EXISTS scm_goods_brand;
DROP TABLE IF EXISTS scm_group_auth;
DROP TABLE IF EXISTS scm_hide_price;
DROP TABLE IF EXISTS scm_inventory_detail;
DROP TABLE IF EXISTS scm_inventory_detail_copy;
DROP TABLE IF EXISTS scm_inventory_single;
DROP TABLE IF EXISTS scm_inventory_single_copy;
DROP TABLE IF EXISTS scm_inventory_single_order_stock;
DROP TABLE IF EXISTS scm_meal_plan;
DROP TABLE IF EXISTS temp_inventory_analysis;
DROP TABLE IF EXISTS scm_predict_order;
DROP TABLE IF EXISTS scm_supply_plan_scm_goods;
DROP TABLE IF EXISTS scm_shop_scm_shop_account;

DROP TABLE IF EXISTS scm_supply_plan;
DROP TABLE IF EXISTS scm_shop_brand;
DROP TABLE IF EXISTS scm_shop_account;
DROP TABLE IF EXISTS scm_organization;
DROP TABLE IF EXISTS scm_seller;
DROP TABLE IF EXISTS scm_seller_account;
DROP TABLE IF EXISTS scm_shopping;
DROP TABLE IF EXISTS scm_storage;
DROP TABLE IF EXISTS scm_storage_position_scm_goods_copy;
DROP TABLE IF EXISTS scm_storehouse_scm_shop;
DROP TABLE IF EXISTS scm_storehouse;
DROP TABLE IF EXISTS scm_supplier_person;
DROP TABLE IF EXISTS scm_supplier;
DROP TABLE IF EXISTS scm_supply_plan;
DROP TABLE IF EXISTS scm_supply_plan_scm_goods;
DROP TABLE IF EXISTS scm_tc_shop;
DROP TABLE IF EXISTS scm_units_of_measure;
DROP TABLE IF EXISTS scm_util;
DROP TABLE IF EXISTS test_flyback;
DROP TABLE IF EXISTS test_flyway;
DROP TABLE IF EXISTS testproduct;
DROP TABLE IF EXISTS testtable;
DROP TABLE IF EXISTS testtable2;
DROP TABLE IF EXISTS user_copy;
DROP TABLE IF EXISTS user_copy1;



