ALTER TABLE scm_supply_plan_scm_goods DROP COLUMN IF EXISTS stock_id;
ALTER TABLE scm_supply_plan_scm_goods DROP COLUMN IF EXISTS good_unit_id;

DROP TABLE IF EXISTS scm_account_role;
DROP TABLE IF EXISTS scm_admin_token;
DROP TABLE IF EXISTS scm_admin;
DROP TABLE IF EXISTS scm_admin_group_scm_shop;
DROP TABLE IF EXISTS scm_storehouse_scm_shop;
DROP TABLE IF EXISTS scm_storehouse;
DROP TABLE IF EXISTS scm_group_auth;
DROP TABLE IF EXISTS scm_admin_group;
DROP TABLE IF EXISTS scm_bulk_picking_routes;
DROP TABLE IF EXISTS scm_bulk_picking;
DROP TABLE IF EXISTS scm_business_district;
DROP TABLE IF EXISTS scm_center_inventory_detail;
DROP TABLE IF EXISTS scm_center_inventory_single;
DROP TABLE IF EXISTS scm_ent_fifo_allocation;
DROP TABLE IF EXISTS scm_ent_details;
DROP TABLE IF EXISTS scm_ent_mail;
DROP TABLE IF EXISTS scm_ent_pallet;
DROP TABLE IF EXISTS scm_ent_stock;
DROP TABLE IF EXISTS scm_finance_mail;
DROP TABLE IF EXISTS scm_goods_brand;
ALTER TABLE scm_goods drop constraint if exists fk_goods_category0;
DROP TABLE IF EXISTS scm_goods_category;
DROP TABLE IF EXISTS scm_goods_img;
DROP TABLE IF EXISTS scm_goods_outbound;
DROP TABLE IF EXISTS scm_goods_price;
DROP TABLE IF EXISTS scm_goods_price_history;
DROP TABLE IF EXISTS scm_hide_price;
DROP TABLE IF EXISTS scm_inventory_detail;
DROP TABLE IF EXISTS scm_inventory_detail_copy;
DROP TABLE IF EXISTS scm_inventory_single;
DROP TABLE IF EXISTS scm_inventory_single_copy;
DROP TABLE IF EXISTS scm_inventory_single_order_stock;
DROP TABLE IF EXISTS scm_mail;
DROP TABLE IF EXISTS scm_meal_plan;
DROP TABLE IF EXISTS scm_menu;
DROP TABLE IF EXISTS scm_order_details_log;
ALTER TABLE scm_order_details drop column if exists stock_order_no;
DROP TABLE IF EXISTS scm_order_stock;
ALTER TABLE scm_shop_brand drop column if exists organization_id;
ALTER TABLE scm_shop_account drop column if exists organization_id;
DROP TABLE IF EXISTS scm_organization;
DROP TABLE IF EXISTS scm_predict_order;
DROP TABLE IF EXISTS scm_price_plan_scm_goods;
ALTER TABLE scm_supply_plan drop column if exists price_plan_id;
DROP TABLE IF EXISTS scm_price_plan;
DROP TABLE IF EXISTS scm_return_goods;
DROP TABLE IF EXISTS scm_return_goods_month;
DROP TABLE IF EXISTS scm_seller;
DROP TABLE IF EXISTS scm_seller_account;
DROP TABLE IF EXISTS scm_sender_mail;
DROP TABLE IF EXISTS scm_sender_mail_log;
DROP TABLE IF EXISTS scm_shopping;
DROP TABLE IF EXISTS scm_shopping_history;
DROP TABLE IF EXISTS scm_storage;
DROP TABLE IF EXISTS scm_storage_position_scm_goods;
DROP TABLE IF EXISTS scm_storage_position_scm_goods_copy;
DROP TABLE IF EXISTS scm_storage_position;
DROP TABLE IF EXISTS scm_small_storage;
ALTER table scm_goods drop column if exists stock_id;
DROP TABLE IF EXISTS scm_stock;
DROP TABLE IF EXISTS scm_storage_facility;
DROP TABLE IF EXISTS scm_storage_goods_log;
DROP TABLE IF EXISTS scm_store_picking_supplyitems;
DROP TABLE IF EXISTS scm_store_picking_supplyitems_vege_routes;
DROP TABLE IF EXISTS scm_suppliers_goods_daily;
DROP TABLE IF EXISTS scm_supplier_price_plan;
DROP TABLE IF EXISTS scm_supplier_person;
DROP TABLE IF EXISTS scm_supplier;
DROP TABLE IF EXISTS scm_supplier_box;
DROP TABLE IF EXISTS scm_supplier_box_scm_supplier;
DROP TABLE IF EXISTS scm_tc_shop;
DROP TABLE IF EXISTS scm_transfer_stock;
DROP TABLE IF EXISTS scm_units_of_measure;
DROP TABLE IF EXISTS scm_user_update_position_log;
ALTER TABLE scm_goods drop column if exists util_id;
DROP TABLE IF EXISTS scm_util;
DROP TABLE IF EXISTS com_main_unit;
DROP TABLE IF EXISTS flyway_schema_history;
DROP TABLE IF EXISTS migration;
DROP TABLE IF EXISTS st_store_account;
DROP TABLE IF EXISTS st_accounts;
DROP TABLE IF EXISTS st_food_item_copy;
DROP TABLE IF EXISTS st_food_item_copy_on;
DROP TABLE IF EXISTS st_ingredient_copy;
ALTER TABLE scm_shop DROP COLUMN IF EXISTS ingredient_type_id;
DROP TABLE IF EXISTS st_ingredient_types;
DROP TABLE IF EXISTS st_inventory_allocation;
DROP TABLE IF EXISTS st_inventory_count;
DROP TABLE IF EXISTS st_inventory_miscount;
DROP TABLE IF EXISTS st_inventory_items;
DROP TABLE IF EXISTS st_member_account;
DROP TABLE IF EXISTS st_menu;
DROP TABLE IF EXISTS st_org;
DROP TABLE IF EXISTS st_safe_store_goods_copy;
DROP TABLE IF EXISTS st_shop_sales_details;
DROP TABLE IF EXISTS st_shop_table;
DROP TABLE IF EXISTS st_shop_section;
DROP TABLE IF EXISTS testproduct;
DROP TABLE IF EXISTS testtable;
DROP TABLE IF EXISTS test_flyway;
DROP TABLE IF EXISTS test_flyback;
DROP TABLE IF EXISTS testtable2;
DROP TABLE IF EXISTS temp_inventory_analysis;

ALTER TABLE scm_goods drop column if exists util_id;
DROP TABLE IF EXISTS scm_util;
DROP TABLE IF EXISTS scm_version;

alter table scm_shop_account drop column if exists create_time;
alter table scm_shop_account drop column if exists serial_num;
alter table scm_shop_account drop column if exists last_login;

ALTER TABLE scm_supply_plan_scm_goods drop column IF EXISTS good_unit_id;
ALTER TABLE scm_supply_plan_scm_goods drop column IF EXISTS stock_id;
ALTER TABLE scm_supply_plan_scm_goods drop constraint if exists scm_supply_plan_scm_goods_good_id_fkey12;
alter table scm_good_units drop column if exists is_count_unit;
alter table scm_good_units drop column if exists is_base_unit;
alter table scm_good_units drop column if exists is_order_unit;
alter table scm_good_units drop column if exists goods_id;
ALTER TABLE scm_goods drop column if exists base_good_unit_id;
ALTER TABLE scm_goods drop column if exists order_good_unit_id;
ALTER TABLE scm_goods drop column if exists count_good_unit_id;
DELETE FROM st_safe_store_goods;

DROP TABLE IF EXISTS scm_good_pricing;
ALTER TABLE st_daily_count_items drop column if exists good_unit_id;
DELETE FROM scm_good_units where supply_plan_goods_id is null;
ALTER TABLE scm_good_units DROP CONSTRAINT IF EXISTS unique_good_id_ratio_to_base;
ALTER TABLE scm_order_details drop column  if exists spec_text;
ALTER TABLE scm_order_details drop column  if exists hide_price;
ALTER TABLE scm_order_details drop column  if exists yu_price;
ALTER TABLE scm_order_details drop column  if exists item_total;
ALTER TABLE scm_order_details drop column  if exists item_total;

DROP EXTENSION IF EXISTS pg_stat_statements;

ALTER TABLE scm_supply_plan_scm_goods DROP COLUMN IF EXISTS status;

ALTER TABLE scm_supply_plan_scm_goods
ALTER COLUMN stock_category_id SET NOT NULL;